# Generated by Django 5.2 on 2025-05-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vpnconnectionlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vpnconnectionlog',
            unique_together={('username', 'ip_address', 'connected_at')},
        ),
    ]
