# Generated by Django 5.2 on 2025-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vpnconnectionlog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnconnectionlog',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
